### ISSUE TITLE
Change the font in a cell

### ISSUE THREAD

**Issue by Jan-E** [felipowsky/FYComboBox#3]
@felipowsky 
cellTextColor was an easy way to change the color in a cell, but there is no easy method to change the font(size). This can be done by adding cellTextFont.

**Comment by Jan-E** [comment]
Please merge PR https://github.com/felipowsky/FYComboBox/pull/2

**Comment by felipowsky** [comment]
I created a new commit (https://github.com/felipowsky/FYComboBox/commit/6d8ffd0a05a87aa06786adfd74dca07577f20b53) to separate your suggestion from `maxRows` discussion (https://github.com/felipowsky/FYComboBox/issues/1).
I've included `cellTextFont` in the 1.1.2 release.

Thanks for your contribution!
