### ISSUE TITLE
View Hierarchy hides combobox with views on top

### ISSUE THREAD

**Issue by shahdhiren** [felipowsky/FYComboBox#4]
```
UIView
    - FYCombobox
    - <Some other view, For eg UILabel>
```

If my label frame is just below the FYComboBox frame, then if FYComboBox expands, then TableView of combobox hides beneath the Label frame.

Let me know if there are any other alternatives apart from changing View hierarchy.
Also, let me know if you plan in any future release for this issue.

**Comment by felipowsky** [comment]
Do you mean like this?

<img width="173" alt="pr1" src="https://cloud.githubusercontent.com/assets/1298990/18568993/6e7c7778-7b76-11e6-847f-c8180f60adc1.png">

You can try changing the order of your view hierarchy.

From this:
<img width="187" alt="pr2" src="https://cloud.githubusercontent.com/assets/1298990/18569016/94181bb8-7b76-11e6-8fba-24e75ae7bff3.png">

To this:
<img width="195" alt="pr3" src="https://cloud.githubusercontent.com/assets/1298990/18569017/9418b8d4-7b76-11e6-8abd-8754a8274d3d.png">

Or version [1.1.3](https://github.com/felipowsky/FYComboBox/commit/cc556b5dcf8a3eb5eb5256473c4341ae38a274bb) now includes new delegates that might be useful:
`comboBox:willOpenAnimated:`
`comboBox:didOpenAnimated:`
`comboBox:willCloseAnimated:`
`comboBox:didCloseAnimated:`

So you could do something like this:
```
- (void)comboBox:(FYComboBox *)comboBox willOpenAnimated:(BOOL)animated
{
    [comboBox.superview bringSubviewToFront:comboBox];
}
```

Does this help?
Thanks for your feedback.

**Comment by shahdhiren** [comment]
Yes this is the exact issue I was facing. 

Thanks a lot @felipowsky. I have already applied the view hierarchy change. But I was expecting so fix from library side. So the delegate method will solve my purpose. Thanks a lot for responding and solving this issue. 👍
